In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
# version of the pytorch
print("PyTorch Version :", torch.__version__)

PyTorch Version : 2.0.1+cu118


In [13]:
# scalar => Zero dimensional data
scalar = torch.tensor(7)

print("Scalar : ", scalar)

Scalar :  tensor(7)


In [6]:
print("Dimensions : ", scalar.ndim)

Dimensions :  0


In [12]:
print("Python Integer :", scalar.item())

print("Scalar tensor data type : ", scalar.dtype)

integer = scalar.item()

print("Data Type : ", type(integer))

Python Integer : 7
Scalar tensor data type :  torch.int64
Data Type :  <class 'int'>


In [16]:
print("Shape scalar : ", scalar.shape)

Shape scalar :  torch.Size([])


In [14]:
# vector => One dimension data
vector = torch.tensor([4, 4])
print("Vector : ", vector)

Vector :  tensor([4, 4])


#### Based on the brackets the dimension would be determined

In [17]:
print("Shape of the vecxtor : ", vector.shape)   # torch[2]) => it describes the two elements placed in the square bracket

Shape of the vecxtor :  torch.Size([2])


In [19]:
# matrix => Two dimensional Data
matrix = torch.tensor([[1, 2], [3, 4]])

print("Matrix : ", matrix)

Matrix :  tensor([[1, 2],
        [3, 4]])


In [21]:
# shape of the matrix
print("Shape Matrix : ", matrix.shape) # torch([2, 3]) => 2 row x 2 col

Shape Matrix :  torch.Size([2, 2])


In [22]:
print("Dimension of matrix : ", matrix.ndim)

Dimension of matrix :  2


In [27]:
# create an tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print("Tensor : ", tensor)

Tensor :  tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [28]:
print("Shape tensor : ", tensor.shape)

Shape tensor :  torch.Size([1, 3, 3])


In [26]:
print("Dimension tensor : ", tensor.ndim)  # Tensor => Three dimensional data

Dimension tensor :  3


In [29]:
# Random tensors
randomTensor = torch.rand(size = (2, 3))

print("Random tensor : ", randomTensor)

Random tensor :  tensor([[0.9076, 0.4325, 0.2479],
        [0.4018, 0.3989, 0.3251]])


In [31]:
print("Shape of random tensor : ", randomTensor.shape)

Shape of random tensor :  torch.Size([2, 3])


In [32]:
print("Dimensionn random tensor : ", randomTensor.ndim)

Dimensionn random tensor :  2


In [37]:
# create an random tensor of shape (244, 244, 3)
imageTensor = torch.rand(size=(244, 244, 3))

# print("Image data tensor : ", imageTensor)

print("Shape image data : ", imageTensor.shape)

print("Dimension image tensor : ", imageTensor.ndim) # Three channels

Shape image data :  torch.Size([244, 244, 3])
Dimension image tensor :  3


In [38]:
# creating zeros and ones in the tensor
zeros = torch.zeros(size=(2, 4))

print("Zeros data : ", zeros)

print("Shape of the data : ", zeros.shape)

print("Dimension of the data : ", zeros.ndim)

print("Data Type of the data : ", zeros.dtype)

Zeros data :  tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape of the data :  torch.Size([2, 4])
Dimension of the data :  2
Data Type of the data :  torch.float32


In [39]:
# creating the tensor fills with the ones data
ones = torch.ones(size=(2, 4))

print("Zeros data : ", ones)

print("Shape of the data : ", ones.shape)

print("Dimension of the data : ", ones.ndim)

print("Data Type of the data : ", ones.dtype)

Zeros data :  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Shape of the data :  torch.Size([2, 4])
Dimension of the data :  2
Data Type of the data :  torch.float32


In [40]:
# create an tensor using range of numbers
# Syntax => torch.arange(start, end, step)
rangeTensor = torch.arange(0, 10) # step is optional

print("Range of numbers : ", rangeTensor)

Range of numbers :  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [45]:
step = torch.arange(0, 11, 2)

print("Range of values with step value : ", step)

print("Shape : ", step.shape)

print("Dimension : ", step.ndim) # vector data

Range of values with step value :  tensor([ 0,  2,  4,  6,  8, 10])
Shape :  torch.Size([6])
Dimension :  1


In [46]:
# create an tensor with the prevous tensor shape
zerosLike = torch.zeros_like(input = step)

print("Zeros like : ", zerosLike)

Zeros like :  tensor([0, 0, 0, 0, 0, 0])


#### Default data type of the tensor was float-32

In [52]:
float_32_Tensor = torch.tensor([1.0, 1.3, 1.5], dtype=None, device=None, requires_grad=True)

In [58]:
print("Default dtype : ", float_32_Tensor)

print("Torch Device : ", float_32_Tensor.device)

print("Shape of the tensor : ", float_32_Tensor.shape)

print("Dtype of the tensor : ", float_32_Tensor.dtype)

Default dtype :  tensor([1.0000, 1.3000, 1.5000], requires_grad=True)
Torch Device :  cpu
Shape of the tensor :  torch.Size([3])
Dtype of the tensor :  torch.float32


In [56]:
float_16_Tensor = torch.tensor([1.7, 2.3, 3.5], dtype=torch.float16)

In [57]:
print("Dtype of the tensor : ", float_16_Tensor.dtype)

Dtype of the tensor :  torch.float16


### Getting information from the tensors

In [61]:
# create an random tensor
infoTensor = torch.rand(2, 4)  # 2 row x 4 col

# Some info from the tensor
print("Tensor : ", infoTensor)

print("Shape of the tensor :", infoTensor.shape)

print("DataTYpe of the tensor : ", infoTensor.dtype)

print("Device associates with the tensor : ", infoTensor.device)

Tensor :  tensor([[0.9035, 0.6229, 0.9084, 0.4088],
        [0.1971, 0.1183, 0.0338, 0.2034]])
Shape of the tensor : torch.Size([2, 4])
DataTYpe of the tensor :  torch.float32
Device associates with the tensor :  cpu


### Manipulate the tensors with various operations

In [63]:
# basic operations on the tensor
# addition, subraction ,multiplication (Element wise)
addTensor = torch.tensor([1,2,3])

addTensor + 10 # adds 10 with the each item in the tesnor

tensor([11, 12, 13])

In [65]:
# multiply by 10
addTensor * 10  # temporary update becoz it would not be store in the variable

tensor([10, 20, 30])

In [66]:
# print the original tensor
print("Original Tensor :", addTensor)

Original Tensor : tensor([1, 2, 3])


In [68]:
# subract operation
# reassign the values
newTensor = addTensor - 10

print("New Tensor : ", newTensor)

New Tensor :  tensor([-9, -8, -7])


In [69]:
# reassign with the addition operation
newTensor = newTensor + 10

print("Updated Tensor : ", newTensor)

Updated Tensor :  tensor([1, 2, 3])


In [72]:
# torch also contains the built in basic operations
torch.add(addTensor, 20)  # it would not update the original tensor

tensor([21, 22, 23])

In [73]:
# Element wise multiplication
print("Element Wise Multiplication")
print(addTensor * addTensor)

Element Wise Multiplication
tensor([1, 4, 9])


In [76]:
# using torch.mul() operation
print(torch.mul(addTensor, addTensor))

print(addTensor * addTensor)

tensor([1, 4, 9])
tensor([1, 4, 9])


### Matrix multiplication (All you need)

# torch.matmul() => used for matrix multiplication

    Rules to be followed for matrix multiplication :
        1. Inner dimensions must be match
            For example :
                * (3, 2) @ (3, 2) won't work
                * (2, 3) @ (3, 2) will work
        2. Resultant matrix has the shape of the outer matrix
            For exmaple :
                * (2, 3) @ (3, 2) -> (2, 2)


In [3]:
# Sample data
data = torch.tensor([1, 2, 3, 4])
print("Shape : ", data.shape)

Shape :  torch.Size([4])


In [4]:
# @ in python would used for element wise multiplication
print("Element Wise Multiplication: ", data * data) # Output: [1, 4, 9, 16]

Element Wise Multiplication:  tensor([ 1,  4,  9, 16])


In [6]:
# torch.matmul() was used for matrix multiplication
print("Matrix Multiplication: ", torch.matmul(data, data)) # Output: tensor(30)

Matrix Multiplication:  tensor(30)


#### Compare Built In matmul() vs User defined


In [9]:
%%time
value = 0
for i in range(len(data)):
    value += data[i] * data[i]
print("Matrix Multiplication user defined: ", value)

Matrix Multiplication user defined:  tensor(30)
CPU times: total: 0 ns
Wall time: 1 ms


In [10]:
%%time
# predefined matrix multiplication
torch.matmul(data, data)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(30)

### Common errors in the deep learning (shape errors)

* Common errors in this was the shape mismatches while matrix multiplication
* It would be solve by alter the matrix inner dimension

In [2]:
# For example
dataA = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
dataB = torch.tensor([[7, 10], [11, 12], [13, 14]], dtype=torch.float32)

try:
    # matrix multiplication
    torch.matmul(dataA, dataB)
except:
    print("RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)")

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [3]:
# modify the tensors inner dimension
print(dataA)
print(dataB.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 11., 13.],
        [10., 12., 14.]])


In [4]:
# perform the matrix multiplication after the change in inner dimension
torch.matmul(dataA, dataB.T)

tensor([[ 27.,  35.,  41.],
        [ 61.,  81.,  95.],
        [ 95., 127., 149.]])

In [11]:
# linear function using torch
#torch.manual_seed(42)

# matrix multiplication
linear = torch.nn.Linear(in_features=2, out_features=6)

x = dataA
output = linear(x)

print(f"Input Shape: {x.shape}\n")
print(f"Output:\n{output}\n\n Output shape: {output.shape}")

Input Shape: torch.Size([3, 2])

Output:
tensor([[-0.2315,  1.4021, -0.8148, -2.3058, -0.9559, -0.8078],
        [-0.5210,  3.1641, -2.9100, -5.0463, -1.0017, -1.5452],
        [-0.8104,  4.9260, -5.0051, -7.7868, -1.0475, -2.2827]],
       grad_fn=<AddmmBackward0>)

 Output shape: torch.Size([3, 6])


#### Aggregate functions

In [13]:
# create an tensor (vector)
data = torch.arange(0, 100, 10)
print(f"Data: {data}")

Data: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [14]:
# aggregate functions
print(f"Maximum: {data.max()}")
print(f"Minimum: {data.min()}")

Maximum: 90
Minimum: 0


In [19]:
print(f"Mean: {data.type(torch.float32).mean()}")

Mean: 45.0


In [20]:
print(f"Sum: {data.sum()}")

Sum: 450


Note: It would be also be avilable in the torch class

In [21]:
# positional min/max
# it would be used to find the index of the maximum and minimum values in the tensor
print(f"Argmax: {data.argmax()}")
print(f"Argmin: {data.argmin()}")

Argmax: 9
Argmin: 0


In [28]:
print(data.dtype)

torch.int64


In [32]:
# add extra dimension to the data
data = data.reshape(1, 10)
data.shape

torch.Size([1, 10])

In [33]:
# view the data
z = data.view(1, 10)
z

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [40]:
z[:, 0] = 1
z

tensor([[ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [43]:
dataStack = torch.stack([z, z, z, z], dim=0)
dataStack

tensor([[[ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]],

        [[ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]],

        [[ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]],

        [[ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]]])

In [46]:
# remove the dimension 1
print("Original Shape:", z.shape)
newData = z.squeeze()
print(f"Remove the 1st dimension: {newData}")
print(f"Shape of the data: {newData.shape}")

Original Shape: torch.Size([1, 10])
Remove the 1st dimension: tensor([ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Shape of the data: torch.Size([10])


In [50]:
# add dimension 1
unSqueeze = newData.unsqueeze(dim=0)
print(unSqueeze.shape)
unSqueeze

torch.Size([1, 10])


tensor([[ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [51]:
!nvidia-smi

Sat Aug 12 13:32:13 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.40                 Driver Version: 536.40       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8              13W /  95W |    158MiB /  6144MiB |      5%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [54]:
torch.cuda.is_available()

True

In [55]:
torch.cuda.device_count()

1