### Simple Neural Network

- Neural network is a function machine.
    - Input (like an image, a number or some data) -> machine -> Output (prediction).
    - The machine has **layers** with **neurons** (like little calculator).
    - Each connection has **weights** (knobs you can turn).
    - Goal: turn the knobs until the machine makes good predictions.

In [2]:
import torch
import torch.nn as nn # neural network module
import torch.optim as optim # optimizer module

##### Building a smallest neural network: Linear Regression

- Imagine predicting house price just from size.

In [3]:
# training data: x = size, y = price
# x is independent data and y is dependent on x
# based on x data point y will react
x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])

# function: y = 2x

In [6]:
# basic model
model = nn.Linear(in_features=1, out_features=1) # in_features -> size, out_features -> price

model

Linear(in_features=1, out_features=1, bias=True)

In [9]:
model.parameters() # it will provide a generator object

<generator object Module.parameters at 0x7f38edbcdd90>

In [11]:
# to inspect the generator object
params = list(model.parameters())
params

[Parameter containing:
 tensor([[-0.0712]], requires_grad=True),
 Parameter containing:
 tensor([0.8496], requires_grad=True)]

In [13]:
# check the shape of the parameters
for p in params:
    print(p.shape)

torch.Size([1, 1])
torch.Size([1])


In [14]:
# check for the trainable parameters
total_params = sum(p.numel() for p in params)

print(f"Total Parameters: {total_params}")

Total Parameters: 2


In [16]:
# for inspect the values
for name, param in model.named_parameters():
    print(name, param.shape)
    print(param)

weight torch.Size([1, 1])
Parameter containing:
tensor([[-0.0712]], requires_grad=True)
bias torch.Size([1])
Parameter containing:
tensor([0.8496], requires_grad=True)


In [17]:
# create a loss and optimizer
loss_fn = nn.MSELoss() # mean squared error
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [24]:
# build a simple training loop
for epoch in range(1000):
    y_pred = model(x) # forward pass
    loss = loss_fn(y_pred, y) # compute error

    optimizer.zero_grad() # clear old gradients
    loss.backward() # compute new gradients
    optimizer.step() # update weights

print(f"Predicted: {model(torch.tensor([[5.0]])).item()}")

Predicted: 9.999994277954102
